package com.adammcquistan.openjfx;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import com.adammcquistan.openjfx.models.Person;


public class AppTest {
    @Test public void testPerson() {
       Person p = new Person("Adam", "McQuistan");
       assertEquals("Adam", p.getFirstName());
       assertEquals("McQuistan", p.getLastName());
    }
}
